dataset:
  base_dir: "/Users/stefanoroybisignano/Desktop/W_SimplexRapid/fine-tuning/translations/data_preprocessing/data/lang_pairs/it-de/3_fineTuning/dpo" # or "/supervised"
fine_tuning:
  enable: true                     # abilita/disabilita il fine-tuning
  base_model: "gpt-4o-2024-08-06"  # modello di base da usare
  method: "supervised"             # o "dpo"
  suffix_template: "{lang_pair}-translator-{version}-{method}"
  hyperparameters:
    n_epochs: 3
    batch_size: 1
    learning_rate_multiplier: 2
evaluation:
  enable: true
  data_source_config_path: "evaluation/config/data_source_config.json"
  testing_criteria_path: "evaluation/config/testing_criteria.json"
  data_source_run_path: "evaluation/config/data_source_run.json"


